### ISSUE TITLE
Please update the React App example to the latest casbin.js version 0.1.0

### ISSUE THREAD

**Issue by dilipkk-foyernet** [casbin-js/examples#1]
We are getting the following errors with the latest version of casbin.js 0.1.0:
/node_modules/casbin/lib/esm/model/model.js 158:32
Module parse failed: Unexpected token (158:32)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   async buildIncrementalRoleLinks(rm, op, sec, ptype, rules) {
|     if (sec === 'g') {
>       await this.model.get(sec)?.get(ptype)?.buildIncrementalRoleLinks(rm, op, rules);
|     }
|   } // buildRoleLinks initializes the roles in RBAC.

Can you please update this example so that we can follow it?

**Comment by hsluoyz** [comment]
@kingiw can you help on this issue?

**Comment by kingiw** [comment]
The React App is also available for Casbin.js v0.0.3. You can specify the dependency version explicitly.

Casbin.js is being updated and we will move this example to support latest Casbin.js later.
